app:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    
_admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    
_web:
    resource: "@WebBundle/Resources/config/routing.yml"